[tool.black]
line-length = 120

[tool.isort]
profile = "black"
lines_after_imports = 2
line_length = 120
combine_as_imports = true
combine_star = true

[tool.pyright]
useLibraryCodeForTypes = true
typeCheckingMode = "strict"
pythonVersion = "3.11"